export const tapes = [
  {
    title:'Nie będzie powrotu',
    year:1993,
    label:'ABC Tapes',
    medium:'Kaseta',
    foto:'/images/niebedzie.jpg',
    description:' Pierwszy niby-studyjny materiał, z tym, że studiem była klasa w mojej szkole, sprzętem - znaleziony przypadkiem w laboratorium elektronicznym mixer, a realizatorem Sexon - nasz kolega z osiedla, który w miarę ogarniał różnegi rodzaju sprzęty, a do tego miał w miarę dobry słuch.',
    songs:[
      {title:'1. Intro', 
        link:''},
      {title:'2. Bunt 1', 
        link:''},
      {title:'3. Beznadzieja (Bunt 2)', 
        link:''},
      {title:'4.Beznadzieja 2 (Bunt 3)', 
        link:''},
      {title:'5. Miś', 
        link:''},
      {title:'6. 2002', 
        link:''},
      {title:'7. Antyskinheads', 
        link:''},
      {title:'8. Narkomania', 
        link:''},
      {title:'9. Kibol', 
        link:''},
      {title:'10. Policyjne skurwysyny', 
        link:''},
      {title:'11. Huta', 
        link:''},
      {title:'12. To samo', 
        link:''},
      {title:'13. Bez przyszłości', 
        link:''},
      {title:'14. Nie będzie powrotu', 
        link:''},
      {title:'15. Apokalipsa', 
        link:''},
      {title:'16.Bilet do wojska', 
        link:''},
      {title:'17. Przemoc', 
        link:''},
      {title:'18. Wojna', 
        link:''},
      {title:'19. Szkoła', 
        link:''},
      {title:'20. Nazi punk fuck off', 
        link:''},
    ]
  },
  {
    title:'Kto zastrzelił dezertera?',
    year:1994,
    label:'Tylko Pank',
    medium:'Kaseta',
    foto:'/images/kto.jpg',
    description:' Pierwszy materiał nagrany w studio - bodajże "Gamma Studio" dla wydawnictwa Tylko Pank',
    songs:[
      {title:'1. Próba mikrofonu', 
        link:''},
      {title:'2. Uciekająca wolność', 
        link:'/audio/Kto/02.mp3'},
      {title:'3. Obraz Twej nienawiści', 
        link:''},
      {title:'4. Biała siła', 
        link:''},
      {title:'5. Historia złotej bransoletki', 
        link:''},
      {title:'6. Nie po to żyjemy', 
        link:''},
      {title:'7. Generacja', 
        link:''},
      {title:'8. Świat anarchistów', 
        link:''},
      {title:'9. Krótka piosenka o jabłku', 
        link:''},
      {title:'10. Słuchaj Jezu', 
        link:''},
      {title:'11. Nie będzie powrotu instrumental', 
        link:''},
      {title:'12. Fuck war', 
        link:''},
      {title:'13. Nic o nas bez nas', 
        link:'/audio/Kto/13.mp3'},
      {title:'14. Gdy będziesz odchodził', 
        link:''},
      {title:'15. Szkoła', 
        link:''},
      {title:'16. Reggae', 
        link:''},
      {title:'17.Czas jest złudzeniem', 
        link:''},
      {title:'18. Nowa wiara', 
        link:''},
      {title:'19. Pasmo niepowodzeń', 
        link:''},
      {title:'20. Ja to wiem', 
        link:''},
      {title:'21. Huta', 
        link:''},
  
    ]
  },
  {
    title:'Mijający czas',
    year:1995,
    label:'Tylko Pank',
    medium:'Kaseta',
    foto:'/images/mijajacy.jpg',
    description:' Drugi materiał nagrany w studio - bodajże "Gamma Studio" dla wydawnictwa Tylko Pank',
    songs:[
      {title:'1. Izba', 
      link:'/audio/Mijajacy/01.mp3'},
    {title:'2. Pięść', 
      link:''},
    {title:'3. 2002', 
      link:''},
    {title:'4. Rasizm', 
      link:''},
    {title:'5. Idziesz na wojnę', 
      link:''},
    {title:'6. Jadą łysi (muz. Black Sabath)', 
      link:''},
    {title:'7. Fałszywy', 
      link:''},
    {title:'8. Ballada...(dla Zbycha)', 
      link:''},
    {title:'9. MIjający czas', 
      link:'/audio/Mijajacy/09.mp3'},
    {title:'10. 1 maj', 
      link:''},
    {title:'11. Ty', 
      link:'/audio/Mijajacy/11.mp3'},
    {title:'12. Mur nienawiści', 
      link:''},
    {title:'13. Kto', 
      link:''},
    {title:'14. Prywatki', 
      link:''},
    {title:'15. Czemu jesteście', 
      link:''},
    {title:'16.Czas rozstania', 
      link:''},
    ]
  },
  {
    title:'Nie będziemy tacy',
    year:2004,
    label:'Jimmy Jazz Records',
    medium:'CD/LP',
    foto:'/images/niebedziemy.jpg',
    description:'Pierwszy materiał wydany na CD (Jimmy Jazz records, nagramy w Diamond Recordings Studio',
    songs:[

      {title:'1. Urzędy', 
      link:''},
    {title:'2. Nie będziemy', 
      link:''},
    {title:'3. Teraz niebo', 
      link:''},
    {title:'4. To oni', 
      link:''},
    {title:'5. Miliardy', 
      link:''},
    {title:'6. Someone`s gonna die (muz. Blitz)', 
      link:''},
    {title:'7. Mój fiat', 
      link:''},
    {title:'8. Nie zabijaj', 
      link:''},
    {title:'9. Fucking life', 
      link:''},
    {title:'10. Bez ostrzeżenia', 
      link:''},
    {title:'11. Michał', 
      link:''},
    {title:'12. Kolejne ofiary', 
      link:''},
    {title:'13. Za pieniądze', 
      link:''},
    {title:'14. Irak', 
      link:''},
    {title:'15. Watch your back (muz. Cock Sparrer)', 
      link:''},
    {title:'16. Dlaczego', 
      link:''},
    {title:'17. AIDS', 
      link:''},
    {title:'18. Instrumentalny', 
      link:''},
    ]
  },

  {
    title:'???????????',
    year:2005,
    label:'JKastracja',
    medium:'CD/LP',
    foto:'/images/niebedziemy.jpg',
    description:'Nigdy nie wydany materiał',
    songs:[

    {title:'1. Skinhead & punk (muz. ACAB)', 
      link:''},
    {title:'2. Nie mówcie nam', 
      link:''},
    {title:'3. W pogoni za kasą', 
      link:''},
    {title:'4. Polska', 
      link:''},
    {title:'5. Musisz Walczyć', 
      link:''},
    {title:'6. Kufel piwa', 
      link:''},
    {title:'7. Moje miasto', 
      link:''},
    {title:'8. Poniedziałek', 
      link:''},
    {title:'9. Walcz o swoje prawa', 
      link:''},
    {title:'10. To co było', 
      link:''},
    {title:'11. Don Kichoci', 
      link:''},
    {title:'12. Stare pryki', 
      link:''},
    {title:'13. Huta 2005', 
      link:''},
    ]
  },
  {
    title:'Prowadź mnie ulico vol.2',
    year:2005,
    label:'Jimmy Jazz Records',
    medium:'CD/VA',
    foto:'/images/prowadz.jpg',
    description:' Druga część składanki prezentującej wykonawców związanych z wytwórnią JIMMY JAZZ RECORDS. O ile pierwsza część samplera zawierała w większości nagrania znane z płyt zrealizowanych w okresie 1995-2004, pochodzących z katalogu Jimmy Jazz Records i jej poprzedniczki, wytwórni Rock’n’roller, o tyle obecne wydawnictwo w zdecydowanej większości zawiera nagrania premierowe, które stanowią zapowiedź kolejnych tytułów z katalogu wytwórni, bądź powstały specjalnie z myślą o tej składance. O sile "Prowadź mnie ulico vol. 2” stanowi bezsprzecznie obecność na niej m.in. nowych nagrań takich tuzów wytwórni jak KOMETY, THE ANALOGS (utwory premierowe + dwie kompozycje dostępne dotychczas tylko na płycie winylowej) czy VESPA i SMAMPARARAS (nowy utwór w wersji koncert6owej) oraz bardzo obiecujących debiutantów pokroju P.D.S., BANG BANG, NOWEGO ŚWIATA czy THE KOLT złożonych z muzyków (i ex-muzyków) grup ROBOTIX i SKARPETA. Doskonała płyta pokazująca stan posiadania JIMMY JAZZ RECORDS w 2005 roku i spora dawka nowych nagrań znanych wykonawców w specjalnej cenie.',
    songs:[

      {title:'1. The Analogs–	Oi! Oi! Oi!', 
      link:''},
    {title:'2. Nowy Świat–	Reve', 
      link:''},
    {title:'3. P.D.S.–	Całkiem Sam', 
      link:''},
    {title:'4. Komety–	W Dżinsach I Swetrze', 
      link:''},
    {title:'5. Anti Dread–	Dzień I Noc', 
      link:''},
    {title:'6. The Hunkies–	Jaki Mam Być?', 
      link:''},
    {title:'7. The Kolt–	Ordynarny Twist', 
      link:''},
    {title:'8. Vespa –	Nie Kłam Już Kotku', 
      link:''},
    {title:'9. Anti Dread–	Wibrator', 
      link:''},
    {title:'10. Bang Bang –	Komputerowe Gry', 
      link:''},
    {title:'11. The Analogs–	Trucizna', 
      link:''},
    {title:'12. P.D.S.–	Szaro-Bury', 
      link:''},
    {title:'13. Skauci–	Instruktor', 
      link:''},
    {title:'14. Beri Beri–	Landryna', 
      link:''},
    {title:'15. Komety–	Tak Mi Źle (Remix)', 
      link:''},
    {title:'16.The Analogs–	Skinhead Girl', 
      link:''},
    {title:'17. Bang Bang –	Nie, Nie, Nie', 
      link:''},
    {title:'18. Nowy Świat–	Atak', 
      link:''},
    {title:'19. Kastracja–Nie Będziemy', 
      link:''},
    {title:'20. Vespa –	Fajny Chłopak', 
      link:''},
    {title:'21. P.D.S.–	Reggae', 
      link:''},
    {title:'22. Eye For An Eye –	Manekin', 
      link:''},
    {title:'23. Exit From Hell–	Złodzieje', 
      link:''},
    {title:'24. Kastracja–	Dlaczego?', 
      link:''},
    {title:'25. Skampararas–	Naturalny Dźwiek (Live)', 
      link:''},
    {title:'26. The Analogs–	Pożegnanie', 
      link:''},
    ]
  },
  {
    title:'Muzyka ulicy muzyka dla mas vol.2',
    year:2005,
    label:'Olifant Records',
    medium:'CD/VA',
    foto:'/images/mumdm2.jpg',
    description:'Na płycie znajdziecie większości dotychczas niepublikowane lub unikatowe nagrania zespolów: Rezystencja, Bulbulators, Gits, all bandits, Junkers, Skankan, PoProstu, Horrorshow, Lumpex75, BTM, Zbeer, Alarm, Sztorm68, Rozbiesz Się, Werwolf77, Bachor, Bilety Do Kontroli, Awantura i Ramzes&theHooligans. ',
    songs:[

    {title:'01. The Gits - Muzyka dla elity', 
      link:''},
    {title:'2. Sztorm 68 - Ten kraj jest nasz', 
      link:''},
    {title:'3. Rezystencja - Wybory 05 ', 
      link:''},
    {title:'4. Awantura - Zasady życia', 
      link:''},
    {title:'5. All bandits - Dzieci ulicy', 
      link:''},
    {title:'6. Game over - Mecz', 
      link:''},
    {title:'7. Contra boys - Respekt i honor', 
      link:''},
    {title:'8. Zbeer - Dzień i noc', 
      link:''},
    {title:'9. The junkers - Zjednoczeni i silni', 
      link:''},
    {title:'10. Ring - Moja nienawiść', 
      link:''},
    {title:'11. Wróg publiczny - Belfast', 
      link:''},
    {title:'12. Zadruga - Goreją wici', 
      link:''},
    {title:'13. Lumpex 75 - Jak pies', 
      link:''},
    {title:'14. Werwolf 77 - Tandeta w modzie', 
      link:''},
    {title:'15. Ramzes & the hooligans -Skok na kiosk', 
      link:''},
    {title:'16.Po prostu - Napierdalamlam dyskomana', 
      link:''},
    {title:'17. Awaria - Pierwszy raz', 
      link:''},
    {title:'18.  Bachor - Przemoc', 
      link:''},
    {title:'19. Skunx - Skinhead', 
      link:''},
    {title:'20. Trinkers - Nasze orły', 
      link:''},
    {title:'21. Kastracja - Musisz walczyć', 
      link:''},
    {title:'22. Skambomambo - Ska made in polska', 
      link:''},
    ]
  },
  {
    title:'Jak Ci minął dzień',
    year:2011,
    label:'Kastracja',
    medium:'CD/LP',
    foto:'/images/jak.jpg',
    description:'Ostatnie nagrania pochodzące z 2011 roku',
    songs:[

      {title:'1. Kastracja', 
      link:''},
    {title:'2. Nie uciekam stąd', 
      link:''},
    {title:'3. Pamiętaj o przyjaźni', 
      link:''},
    {title:'4. Jak Ci minął dzień', 
      link:''},
    {title:'5. Jest jescze takie miejsce', 
      link:''},
    {title:'6. Alkohol szkodzi zdrowiu (muz. Pluton Svea)', 
      link:''},
    {title:'7. Asocjalny', 
      link:''},
    {title:'8. 20 razy 2', 
      link:''},
    {title:'9. Wspomnień czar', 
      link:''},
    {title:'10. Kolejne kłamstwa', 
      link:''},
    {title:'11. Mam słaby łeb', 
      link:''},
    {title:'12. Koledzy albo życie', 
      link:''},
    {title:'13. Uniknęliśmy kary', 
      link:''},
    {title:'14. Szklany mur', 
      link:''},
    ]
  },
  
  {
    title:'Muzyka ulicy muzyka dla mas vol.3',
    year:2014,
    label:'Olifant Records',
    medium:'CD/VA',
    foto:'/images/mumdm3.jpg',
    description:'Na płycie znajdziecie większości dotychczas niepublikowane lub unikatowe nagrania zespolów: Rezystencja, Bulbulators, Gits, all bandits, Junkers, Skankan, PoProstu, Horrorshow, Lumpex75, BTM, Zbeer, Alarm, Sztorm68, Rozbiesz Się, Werwolf77, Bachor, Bilety Do Kontroli, Awantura i Ramzes&theHooligans. ',
    songs:[

    {title:'01. Skunx–	Wystarczy Iskra', 
      link:''},
    {title:'2. Contra Boys–	Zasady Życia', 
      link:''},
    {title:'3. Junkers*–	Serce Chuligana ', 
      link:''},
    {title:'4. Lumpex 75*–	Westerplatte', 
      link:''},
    {title:'5. Faul–	Razem', 
      link:''},
    {title:'6. Hippie Raus–	Hippie Raus', 
      link:''},
    {title:'7. Contra Boys–	Nie Widzisz Przyszłości', 
      link:''},
    {title:'8. Stalag –	Technokultura', 
      link:''},
    {title:'9. Komando Bimber–	W Pętli Czasu', 
      link:''},
    {title:'10. Kastracja–	Pamiętaj O Przyjaźni', 
      link:''},
    {title:'11. Prawy Prosty–	Honor I Duma', 
      link:''},
    {title:'12. The Gits–	Sasza Boy', 
      link:''},
    {title:'13. All Bandits–	Pod Prąd / Czerwone Skurwysyny', 
      link:''},
    {title:'14. Krawal Banda–	Wyliczanka', 
      link:''},
    {title:'15. Dewastators–	Jeszcze Jeden Łyk', 
      link:''},
    {title:'16. Halabarda–	Święty Grall', 
      link:''},
    {title:'17. Dewastators–	Przyziemne Sprawy', 
      link:''},
    {title:'18.  Midgard –	Ragnarok', 
      link:''},
    {title:'19. The Gits–	Między Dwoma Rzekami', 
      link:''},
    {title:'20. Prawy Prosty–	Pokolenie Nienawiści', 
      link:''},
    {title:'21. Gan –	Generał Maczek', 
      link:''},
    {title:'22. Junkers*–	Mowa Nienawiści', 
      link:''},
    {title:'23. Motor Dead–	Dobry Kij', 
      link:''},
    ]
  },

]

