export const tapes = [
  {
    title:'Nie będzie powrotu',
    year:1993,
    label:'ABC Tapes',
    medium:'Kaseta',
    foto:'/images/niebedzie.jpg',
    description:' Pierwszy niby-studyjny materiał, z tym, że studiem była klasa w mojej szkole, sprzętem - znaleziony przypadkiem w laboratorium elektronicznym mixer, a realizatorem Sexon - nasz kolega z osiedla, który w miarę ogarniał różnegi rodzaju sprzęty, a do tego miał w miarę dobry słuch.',
    songs:[
      '1. Intro', 
      '2. Bunt 1',
      '3. Beznadzieja (Bunt 2)',
      '4. Beznadzieja (Bunt 4)',
      '5. Miś',
      '6. 2002',
      '7. Antyskinheads',
      '8. Narkomania',
      '9. Kibol',
      '10. Policyjne skurwysyny',
      '11. Huta',
      '12. To samo',
      '13. Bez przyszłości',
      '14. Nie będzie powrotu',
      '15. Apokalipsa',
      '16. Bilet do wojska',
      '17. Przemoc',
      '18. Wojna',
      '19. Szkoła',
      '20. Nazi Punk Fuck Off',
    ]
  },
  {
    title:'Kto zastrzelił dezertera?',
    year:1994,
    label:'Tylko Pank',
    medium:'Kaseta',
    foto:'/images/kto.jpg',
    description:' Pierwszy materiał nagrany w studio - bodajże "Gamma Studio" dla wydawnictwa Tylko Pank',
    songs:[
      '1. Uciekająca wolność', 
      '2. Obraz Twej nienawiści',
      '3. Białą siła',
      '4. Historia złotej bransoletni',
      '5. Nie po to żyjemy',
      '6. Generacja',
      '7. Świat anrchistów',
      '8. Krótka piosenka o jabłku',
      '9. Słuchaj Jezu',
      '10. Nie będzie powrotu instrumental',
      '11. Fuck War',
      '12. Nic o nas bez nas',
      '13. Gdy będziesz odchodził',
      '14. Szkoła',
      '15. Reggae',
      '16. Czas jest złudzeniem',
      '17. Nowa wiara',
      '18. Pasmo niepowodzeń',
      '19. Ja to wiem',
      '20. Huta',
    ]
  },
  {
    title:'Mijający czas',
    year:1995,
    label:'Tylko Pank',
    medium:'Kaseta',
    foto:'/images/mijajacy.jpg',
    description:' Drugi materiał nagrany w studio - bodajże "Gamma Studio" dla wydawnictwa Tylko Pank',
    songs:[
      '1. Izba', 
      '2. Pięść',
      '3. 2002',
      '4. Rasizm',
      '5. Idziesz na wojnę',
      '6. Jadą łysi (muz. Black Sabath)',
      '7. Fałszywy',
      '8. Ballada...(dla Zbycha)',
      '9. Mijający czas',
      '10. 1 maj',
      '11. Ty',
      '12. Mur nienawiści',
      '13. Kto',
      '14. Prywatki',
      '15. Czemu jesteście',
      '16. Czas rozstania',
    ]
  },

]